spring:
  config:
    activate:
      on-profile: dit

  datasource:
    url: jdbc:postgresql://postgresql.af-dit:5432/af_novadesk

  rabbitmq:
    host: rabbitmq.af-dit
    port: 5672

  boot:
    admin:
      client:
        url: http://spring-boot-admin.af-dit:9191

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://af-authhub.af-infra-core-dit/.well-known/jwks.json
          issuer-uri: https://authhub.dit.auroraforge.co

app:
  openapi:
    server-url: https://novadesk-api.dit.auroraforge.co
  authhub:
    base-url: http://af-authhub.af-infra-core-dit
  cors:
    allowed-origins: "*"

  minio:
    url: http://minio.af-dit:9000
    bucket: af-novadesk-dit
    region: us-east-1

logging:
  level:
    root: INFO
    com.af: DEBUG
    org.apache.coyote.http11.Http11Processor: ERROR
    org.apache.coyote.http11.Http11InputBuffer: ERROR
    io.lettuce.core: WARN
    io.lettuce.core.protocol: WARN
    org.springframework.jdbc.datasource.DataSourceUtils: WARN
    com.zaxxer.hikari: WARN
    org.springframework.security.web.FilterChainProxy: WARN
    org.springframework.security.web.authentication.AnonymousAuthenticationFilter: WARN
    org.springframework.web.servlet.DispatcherServlet: WARN
    org.springframework.web.servlet.mvc.method.annotation: WARN
    de.codecentric.boot.admin.client.registration: WARN
    org.springframework.boot.actuator.endpoint.web.servlet: WARN
