spring:
  config:
    activate:
      on-profile: sit

  datasource:
    url: jdbc:postgresql://postgresql.af-sit:5432/af_novadesk

  rabbitmq:
    host: rabbitmq.af-sit
    port: 5672

  boot:
    admin:
      client:
        url: http://spring-boot-admin.af-sit:9191

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://af-authhub.af-infra-core-sit:8080/.well-known/jwks.json
          issuer-uri: https://authhub.sit.auroraforge.co

app:
  openapi:
    server-url: https://novadesk-api.sit.auroraforge.co
  authhub:
    base-url: http://af-authhub.af-infra-core-sit:8080
  cors:
    allowed-origins:
      - "https://novadesk.sit.auroraforge.co"

  minio:
    url: http://minio.af-sit:9000
    bucket: af-novadesk-sit
    region: us-east-1

logging:
  level:
    root: INFO
    org.apache.coyote.http11.Http11Processor: ERROR
    org.apache.coyote.http11.Http11InputBuffer: ERROR
    io.lettuce.core: WARN
    io.lettuce.core.protocol: WARN
    org.springframework.jdbc.datasource.DataSourceUtils: WARN
    com.zaxxer.hikari: WARN
    de.codecentric.boot.admin.client.registration: WARN
